"""Amstrad CPC colours and the A.P.E.R. RUNNER game palette (single source).

Run as a script to (re)generate:
  gfx/palette/aper_game.gpl   - palette for Aseprite (index = CPC pen)
  src/data/palette.asm        - hardware colour numbers for the gate array
"""

import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# firmware colour number -> (name, RGB, gate array hardware number)
CPC_COLOURS = {
    0: ("Black", 0x000000, 0x14),
    1: ("Blue", 0x000080, 0x04),
    2: ("Bright Blue", 0x0000FF, 0x15),
    3: ("Red", 0x800000, 0x1C),
    4: ("Magenta", 0x800080, 0x18),
    5: ("Mauve", 0x8000FF, 0x1D),
    6: ("Bright Red", 0xFF0000, 0x0C),
    7: ("Purple", 0xFF0080, 0x05),
    8: ("Bright Magenta", 0xFF00FF, 0x0D),
    9: ("Green", 0x008000, 0x16),
    10: ("Cyan", 0x008080, 0x06),
    11: ("Sky Blue", 0x0080FF, 0x17),
    12: ("Yellow", 0x808000, 0x1E),
    13: ("White", 0x808080, 0x00),
    14: ("Pastel Blue", 0x8080FF, 0x1F),
    15: ("Orange", 0xFF8000, 0x0E),
    16: ("Pink", 0xFF8080, 0x07),
    17: ("Pastel Magenta", 0xFF80FF, 0x0F),
    18: ("Bright Green", 0x00FF00, 0x12),
    19: ("Sea Green", 0x00FF80, 0x02),
    20: ("Bright Cyan", 0x00FFFF, 0x13),
    21: ("Lime", 0x80FF00, 0x1A),
    22: ("Pastel Green", 0x80FF80, 0x19),
    23: ("Pastel Cyan", 0x80FFFF, 0x1B),
    24: ("Bright Yellow", 0xFFFF00, 0x0A),
    25: ("Pastel Yellow", 0xFFFF80, 0x03),
    26: ("Bright White", 0xFFFFFF, 0x0B),
}

# pen -> (firmware colour, editor RGB, use). The editor RGB differs from the
# real colour only for pen 15, so it can be told apart from pen 13 in images.
LAMP_EDITOR_RGB = 0xFE0000
GAME_PALETTE = [
    (0, None, "outlines, shadows"),
    (1, None, "deep shadows"),
    (13, None, "asphalt, rails, concrete"),
    (26, None, "road marks, highlights"),
    (3, None, "sleepers, roof tiles, brown"),
    (15, None, "train details, lights"),
    (12, None, "coin shade, dry grass, ballast"),
    (24, None, "coins, yellow vehicles"),
    (9, None, "dark foliage"),
    (21, None, "light foliage"),
    (11, None, "glass, water"),
    (2, None, "buses, train liveries"),
    (16, None, "skin"),
    (6, None, "player clothes, signage"),
    (25, None, "RESERVED: coin glint (cycles 25/26)"),
    (6, LAMP_EDITOR_RGB, "RESERVED: signal lamp (cycles 6/18)"),
]


def rgb_tuple(value):
    return ((value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF)


def editor_rgb(pen):
    firmware, override, _ = GAME_PALETTE[pen]
    return rgb_tuple(override if override is not None else CPC_COLOURS[firmware][1])


def editor_rgb_to_pen():
    """RGB tuple -> pen, for converting images drawn with the game palette."""
    table = {}
    for pen in range(16):
        table.setdefault(editor_rgb(pen), pen)
    return table


def hardware_colour(pen):
    return CPC_COLOURS[GAME_PALETTE[pen][0]][2]


def write_gpl(path):
    lines = ["GIMP Palette", "Name: A.P.E.R. RUNNER game", "Columns: 8", "#"]
    for pen, (firmware, _, use) in enumerate(GAME_PALETTE):
        r, g, b = editor_rgb(pen)
        lines.append(f"{r:3d} {g:3d} {b:3d}\tpen {pen:2d} fw {firmware:2d} {CPC_COLOURS[firmware][0]} - {use}")
    _write(path, "\n".join(lines) + "\n")


def write_asm(path):
    lines = [
        "; generated by tools/cpcpalette.py - do not edit",
        "; game palette: hardware colour numbers for pens 0-15",
        "game_palette:",
    ]
    for pen, (firmware, _, use) in enumerate(GAME_PALETTE):
        lines.append(f"                defb #{hardware_colour(pen):02X}            ; pen {pen:2d}: fw {firmware:2d} {CPC_COLOURS[firmware][0]} - {use}")
    lines += [
        "",
        f"PEN_GLINT       equ 14",
        f"PEN_LAMP        equ 15",
        f"HW_PASTEL_YELLOW equ #{CPC_COLOURS[25][2]:02X}",
        f"HW_BRIGHT_WHITE equ #{CPC_COLOURS[26][2]:02X}",
        f"HW_BRIGHT_RED   equ #{CPC_COLOURS[6][2]:02X}",
        f"HW_BRIGHT_GREEN equ #{CPC_COLOURS[18][2]:02X}",
    ]
    _write(path, "\n".join(lines) + "\n")


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


if __name__ == "__main__":
    write_gpl(os.path.join(ROOT, "gfx", "palette", "aper_game.gpl"))
    write_asm(os.path.join(ROOT, "src", "data", "palette.asm"))
