"""Compiles the screen texts (text/<language>.txt) into font glyph indices.

Every language file has the same names. Each line "name: text" becomes a
string "defb ...,#FF" in src/data/text.asm (bank C7), with one pointer table
per language (text_ptrs_<language>, in LANGUAGES order). The game copies the
table of the language in use to text_ptrs in main RAM, and
src/data/text_ids.asm gives "txt_<name> equ text_ptrs+2*i": the code reads
a text with "ld hl,(txt_<name>)". Characters map to the font sheet
(tools/assets.py FONT_GLYPHS). Accents are dropped, so the texts are written
in capitals.
"""

import os
import sys
import unicodedata

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import assets  # noqa: E402
from cpcpalette import ROOT  # noqa: E402

LANGUAGES = ("en", "el")                # language 0 is the default
TEXT_DIR = os.path.join(ROOT, "text")
OUT = os.path.join(ROOT, "src", "data", "text.asm")
OUT_IDS = os.path.join(ROOT, "src", "data", "text_ids.asm")
END = 0xFF

GLYPH = {}
for index, (_, chars) in enumerate(assets.FONT_GLYPHS):
    for ch in chars:
        GLYPH[ch] = index


class TextError(Exception):
    pass


def glyphs(text, where=""):
    out = []
    for ch in unicodedata.normalize("NFD", text):
        if unicodedata.combining(ch):
            continue                                    # accents
        if ch not in GLYPH:
            raise TextError(f"{where}: no glyph for {ch!r} in {text!r}")
        out.append(GLYPH[ch])
    return out


def load(path):
    texts = {}
    with open(path, encoding="utf-8") as f:
        for number, line in enumerate(f, 1):
            line = line.rstrip("\n")
            if not line.strip() or line.startswith("#"):
                continue
            name, sep, text = line.partition(":")
            if not sep or not name.strip().isidentifier():
                raise TextError(f"{path}:{number}: expected 'name: text'")
            texts[name.strip()] = glyphs(text.strip(), f"{path}:{number}")
    return texts


def load_all(text_dir=TEXT_DIR):
    """{language: {name: glyphs}}, all languages with the same names in the
    same order."""
    languages = {lang: load(os.path.join(text_dir, f"{lang}.txt")) for lang in LANGUAGES}
    names = list(languages[LANGUAGES[0]])
    for lang, texts in languages.items():
        if list(texts) != names:
            missing = set(names) ^ set(texts)
            raise TextError(f"text/{lang}.txt: names differ from text/{LANGUAGES[0]}.txt"
                            f" ({', '.join(sorted(missing)) or 'order'})")
    return languages


def main():
    try:
        languages = load_all()
    except TextError as e:
        print(f"mktext: {e}", file=sys.stderr)
        return 1
    names = list(languages[LANGUAGES[0]])
    ids = ["; generated by tools/mktext.py from text/*.txt - do not edit",
           f"TXT_END equ #{END:02X}",
           f"TXT_COUNT equ {len(names)}",
           f"LANGUAGES equ {len(LANGUAGES)}"]
    for index, (name, _) in enumerate(assets.FONT_GLYPHS):
        ids.append(f"GLYPH_{name.upper()} equ {index}")
    for index, name in enumerate(names):
        ids.append(f"txt_{name} equ text_ptrs+{2 * index}")
    lines = ["; generated by tools/mktext.py from text/*.txt - do not edit",
             "text_ptr_tables:"]
    lines += [f"                defw text_ptrs_{lang}" for lang in LANGUAGES]
    for lang, texts in languages.items():
        lines.append(f"text_ptrs_{lang}:")
        lines += [f"                defw text_{lang}_{name}" for name in names]
    for lang, texts in languages.items():
        for name, codes in texts.items():
            lines.append(f"text_{lang}_{name}:")
            lines.append("                defb " + ",".join(str(c) for c in codes + [END]))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    for path, content in ((OUT_IDS, ids), (OUT, lines)):
        with open(path, "w") as f:
            f.write("\n".join(content) + "\n")
    print(f"text       {len(names):3d} texts x {len(LANGUAGES)} languages"
          f" -> {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
