"""Full-width screen picture -> screen memory for the loading screen.

Input: an indexed PNG of 192 x ROWS*8 mode 0 pixels whose palette indices
are the inks (assets/loading/loading_cpc.png, from tools/mkloading.py or the
Blender pipeline) and its palette list (loading_palette.txt: ink, fw colour).
Output:
  src/data/loading.bin         16K for &C000: 96 bytes per line, line y at
                               (y & 7) * #800 + (y >> 3) * 96 (CRTC R1 = 48)
  src/data/loading_palette.asm firmware colours of inks 0-15
"""

import os
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import png2cpc  # noqa: E402
from cpcpalette import ROOT  # noqa: E402

SRC = os.path.join(ROOT, "assets", "loading", "loading_cpc.png")
PALETTE = os.path.join(ROOT, "assets", "loading", "loading_palette.txt")
OUT = os.path.join(ROOT, "src", "data", "loading.bin")
OUT_PAL = os.path.join(ROOT, "src", "data", "loading_palette.asm")
WIDTH, ROW_BYTES = 192, 96
MAX_ROWS = 2048 // ROW_BYTES                      # rows of 96 bytes in a 2K plane


def convert(path=SRC):
    img = Image.open(path)
    if img.mode != "P" or img.width != WIDTH or img.height % 8 or img.height // 8 > MAX_ROWS:
        raise SystemExit(f"scr2cpc: {path}: need an indexed {WIDTH} x (8*n <= {8 * MAX_ROWS}) image")
    screen = bytearray(16384)
    for y in range(img.height):
        base = (y & 7) * 0x800 + (y >> 3) * ROW_BYTES
        for x in range(0, WIDTH, 2):
            left, right = img.getpixel((x, y)), img.getpixel((x + 1, y))
            if left > 15 or right > 15:
                raise SystemExit(f"scr2cpc: ink > 15 at ({x},{y})")
            screen[base + x // 2] = png2cpc.encode_pixel(left, 0) | png2cpc.encode_pixel(right, 1)
    return screen, img.height // 8


def main():
    screen, rows = convert()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "wb") as f:
        f.write(screen)
    inks = []
    with open(PALETTE) as f:
        for line in f:
            parts = line.split()
            if len(parts) >= 3 and parts[1] == "fw":
                inks.append(int(parts[2]))
    if len(inks) != 16:
        raise SystemExit(f"scr2cpc: {PALETTE}: 16 inks expected")
    with open(OUT_PAL, "w") as f:
        f.write("; generated by tools/scr2cpc.py - do not edit\n")
        f.write(f"LOADING_ROWS equ {rows}\n")
        f.write("loading_palette:\n                defb " + ",".join(map(str, inks)) + "\n")
    print(f"loading    {rows} rows -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
